{% set name = "junit2html" %}
{% set version = "30.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b46fdd832880484754ceed49443b6dd37c27e27e972ebfe7dca920b7a7a29cf9

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  commands:
    - junit2html --help  # [unix]
  imports:
    - junit2htmlreport
    - junit2htmlreport.matrix
    - junit2htmlreport.merge
    - junit2htmlreport.parser
    - junit2htmlreport.runner
    - junit2htmlreport.tag
    - junit2htmlreport.textutils

about:
  home: https://gitlab.com/inorton/junit2html
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate HTML reports from Junit results

extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
